package:
  name: q2-sample-classifier
  version: {{ PLUGIN_VERSION }}
source:
  path: ..
build:
  script: make install
requirements:
  host:
  - python {{ python }}
  - setuptools
  - versioningit
  - wheel
  run:
  - python {{ python }}
  - pandas {{ pandas }}
  - scipy {{ scipy }}
  - numpy {{ numpy }}
  - joblib
  - scikit-learn {{ scikit_learn }}
  - scikit-bio {{ scikit_bio }}
  - seaborn >=0.8
  - fastcluster
  - qiime2 >={{ qiime2 }}
  - q2-types >={{ q2_types }}
  - q2templates >={{ q2templates }}
  - q2-feature-table >={{ q2_feature_table }}
  build:
  - python {{ python }}
  - setuptools
  - versioningit
test:
  commands:
  - py.test --pyargs q2_sample_classifier
  requires:
  - qiime2 >={{ qiime2 }}
  - q2-types >={{ q2_types }}
  - q2templates >={{ q2templates }}
  - q2-feature-table >={{ q2_feature_table }}
  - pytest
  imports:
  - q2_sample_classifier
  - qiime2.plugins.sample_classifier
about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
