{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-sample-classifier
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - pandas {{ pandas }}
    - scipy {{ scipy }}
    - numpy
    - joblib
    - scikit-learn {{ scikit_learn }}
    - scikit-bio {{ scikit_bio }}
    - seaborn >=0.8
    - fastcluster
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - q2templates {{ qiime2_epoch }}.*
    - q2-feature-table {{ qiime2_epoch }}.*

test:
  requires:
    - qiime2 >={{ qiime2 }}
    - q2-types >={{ q2_types }}
    - q2templates >={{ q2templates }}
    - q2-feature-table >={{ q2_feature_table }}
    - pytest

  imports:
    - q2_sample_classifier
    - qiime2.plugins.sample_classifier

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
