{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-sample-classifier
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - pandas
    - scipy
    - joblib
    - scikit-learn
    - scikit-bio
    - seaborn >=0.8
    - fastcluster
    - qiime2 {{ release }}.*
    - q2-types {{ release }}.*
    - q2templates {{ release }}.*
    - q2-feature-table {{ release }}.*

test:
  imports:
    - q2_sample_classifier
    - qiime2.plugins.sample_classifier

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
